name: Mark job status

on:
  workflow_dispatch:
    inputs:
      status:
        description: "applied | ignored | new | closed"
        required: true
        default: "applied"
      url:
        description: "Job URL (exactly as in jobs.md)"
        required: true
      note:
        description: "Optional note"
        required: false
        default: ""

jobs:
  mark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Mark status
        run: |
          python ai-career/scripts/mark_job.py "${{ inputs.status }}" "${{ inputs.url }}" "${{ inputs.note }}"

      - name: Re-score
        run: |
          python ai-career/scripts/score_jobs.py

      - name: Commit outputs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add \
            ai-career/data/state.json \
            ai-career/data/scored_jobs.json \
            ai-career/data/scored_jobs.md || true

          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git commit -m "Update job status"
          git push
